name: Extract Data from QQ Docs

on:
  push:
    branches:
      - main # 触发分支，可以根据需要修改
  workflow_dispatch: # 允许手动触发

jobs:
  extract_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run Docker container
        run: |
          docker build -t extract-app .
          docker run extract-app
